spring:
  threads:
    virtual:
      enabled: true
  config:
    import: application-locale.properties
  application:
    name: ProductCatalogService
  servlet:
    multipart:
      max-file-size: ${MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${MULTIPART_MAX_REQUEST_SIZE}
  mvc:
    apiversion:
      supported: 1.0
      default: 1.0
      use:
        path-segment: 0
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    max-swallow-size: -1